In [1]:
import cv2
img=cv2.imread("/home/kushagra/Documents/code/AI/opencv-course/Resources/Photos/cat.jpg",1)
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
img=cv2.imread("/home/kushagra/Documents/code/AI/opencv-course/Resources/Photos/cat.jpg",-1)
img=cv2.resize(img,(0,0),fx=0.5,fy=0.5)
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
import cv2 as cv
img=cv.imread("/home/kushagra/Documents/code/AI/opencv-course/Resources/Photos/cat.jpg",-1)
img=cv.rotate(img,cv.ROTATE_90_COUNTERCLOCKWISE)
cv.imshow('images',img)
cv.waitKey(0)
cv.destroyAllWindows()

In [4]:
import cv2 as cv
img=cv.imread("/home/kushagra/Documents/code/AI/opencv-course/Resources/Photos/cat.jpg",-1)
img=cv.rotate(img,cv.ROTATE_90_COUNTERCLOCKWISE)
cv.imwrite("new.jpg",img)
cv.imshow('images',img)
cv.waitKey(0)
cv.destroyAllWindows()

In [5]:
import cv2 as cv
import random
img=cv.imread("/home/kushagra/Documents/code/AI/opencv-course/Resources/Photos/cat.jpg",-1)
print(img[200][2:12])
print(type(img))
print(img.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
(427, 640, 3)


In [6]:
import cv2 as cv
import random
img=cv.imread("/home/kushagra/Documents/code/AI/opencv-course/Resources/Photos/cat.jpg",-1)
for i in range(100):
    for j in range(img.shape[1]):
        img[i][j]=[random.randint(0,255),random.randint(0,255),random.randint(0,255)]
cv.imshow('isdi',img)
cv.waitKey(0)
cv.destroyAllWindows()

In [7]:
import cv2
img=cv2.imread("/home/kushagra/Documents/code/AI/opencv-course/Resources/Photos/cat.jpg",1)
tag=img[200:300,500:600]
img[100:200,500:600]=tag
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()